In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
type(a)  # checar tipo de variável

numpy.ndarray

In [ ]:
a.dtype  # checar o tipo de dado

dtype('int64')

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[0]

1

In [ ]:
a[2]

3

In [ ]:
a[0]=10

In [ ]:
a[0]

10

In [ ]:
a

array([10,  2,  3])

In [ ]:
a[0]=1.2


In [ ]:
a

array([1, 2, 3])

In [ ]:
array = np.array([1, 2, 'LC', 4])

In [ ]:
array   # o array converte todos os elementos para string. Numpy não aceita dados com tipos diferentes

array(['1', '2', 'LC', '4'], dtype='<U21')

## existe uma hierarquia: string, float e inteiro

In [ ]:
a

array([1, 2, 3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
a.shape

(3,)

In [ ]:
b = np.array([
              [9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]
])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
c = np.array([
              [1, 2, 1],
              [3, 0, 1],
              [0, 2, 4]
])

In [ ]:
print(c)

[[1 2 1]
 [3 0 1]
 [0 2 4]]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
print(a.ndim)

1


In [ ]:
print(a.shape)

(5,)


In [ ]:
print(a.size)

5


In [ ]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [ ]:
print(b.ndim)

2


In [ ]:
print(b.shape)

(2, 3)


In [ ]:
print(b.size)

6


In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19, 20, 21]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [ ]:
a[2,4]

19

In [ ]:
a[2][4]

19

In [ ]:
a[2,-2]

20

In [ ]:
a[:,2]  # todas as linhas da coluna 2

array([ 3, 10, 17])

In [ ]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[0,2]=99

In [ ]:
a


array([[ 5,  5,  5,  5, 50,  5,  5],
       [ 5,  5,  5,  5, 50,  5,  5],
       [ 5,  5,  5,  5, 50,  5,  5]])

In [ ]:
a[:,4]=50

In [ ]:
a

array([[ 1,  2,  3,  4, 50,  6,  7],
       [ 8,  9, 10, 11, 50, 13, 14],
       [15, 16, 17, 18, 50, 20, 21]])

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a+=7

In [ ]:
a

array([ 8,  9, 10, 11])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

In [ ]:
a+b

array([2, 2, 4, 4])

In [ ]:
a*b

array([1, 0, 3, 0])

In [ ]:
a**b

array([1, 1, 3, 1])

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.mean(stats)

3.5

In [ ]:
np.std(stats)

1.707825127659933

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis=1)  # qual o menor valor na 1a linha e qual o menor valor na 2a linha

array([1, 4])

In [ ]:
# linha
stats.sum(axis=1)

array([ 6, 15])

In [ ]:
# coluna
stats.sum(axis=0)

array([5, 7, 9])

In [ ]:
mat = np.array([1,10,20,30]).reshape(2, 2)   # matriz passa a ter 2 linhas e 2 colunas

In [ ]:
mat

array([[ 1, 10],
       [20, 30]])

In [ ]:
mat.shape   # pra confirmar a mudança da matriz

(2, 2)

In [ ]:
mat[mat > 10]

array([20, 30])

In [ ]:
mat_2 = mat>10    # os Falses é zerado e os Trues permanecem
mat*mat_2

array([[ 0,  0],
       [20, 30]])

In [ ]:
filt = (mat > 10) & (mat <= 25)
mat[filt]

array([20])

In [ ]:
mat

array([[ 1, 10],
       [20, 30]])

In [ ]:
filt = (mat == 1) | (mat > 20)
mat[filt]

array([ 1, 30])

In [ ]:
filt = (mat > 10) & (mat <= 25) # quer <= 10 ou > 25
mat[~filt]

array([ 1, 10, 30])

In [ ]:
mat[~((mat >10) & (mat <=25))]

array([ 1, 10, 30])

In [ ]:
u = np.array([-1, 2, -3])
print("u =", u)
print()

u = [-1  2 -3]



In [ ]:
u<0

array([ True, False,  True])

In [ ]:
u[u<0] # retorna só os valores negativos

array([-1, -3])

In [ ]:
u[u<0] = 0

In [ ]:
u

array([0, 2, 0])

In [ ]:
np.where(u<0,0,u)  # onde u<0 substitua por 0, ao contrário mantenha u
# np.where(se condição, recebe valor, se não)

array([0, 2, 0])

In [ ]:
# Nans, os not a number são representados por np.nan

In [ ]:
a = np.array([[1, 2, 3, np.nan, 5], [np.nan, 7, 8, 9, 10]])
a

array([[ 1.,  2.,  3., nan,  5.],
       [nan,  7.,  8.,  9., 10.]])

In [ ]:
# podemos identificar os nans com o método np.isnan(a)

In [ ]:
np.isnan(a)

array([[False, False, False,  True, False],
       [ True, False, False, False, False]])

In [ ]:
np.isnan(a).sum()   # somando os Trues ele diz quantos são os nans

2