# Algoritmos de ordenação

## Bubble sort

In [ ]:
import numpy as np

In [ ]:
def bubble_sort(vetor):
  n = len(vetor)

  for i in range(n):
    for j in range(0, n - i - 1):
      if vetor[j] > vetor[j + 1]:
        temp = vetor[j]
        vetor[j] = vetor[j + 1]
        vetor[j + 1] = temp
  return vetor

In [ ]:
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selection sort

In [ ]:
def selection_sort(vetor):
  n = len(vetor)

  for i in range(n):
    id_minimo = i
    for j in range(i + 1, n):
      if vetor[id_minimo] > vetor[j]:
        id_minimo = j
    temp = vetor[i]
    vetor[i] = vetor[id_minimo]
    vetor[id_minimo] = temp
  
  return vetor

In [ ]:
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Insertion sort

In [ ]:
def insertion_sort(vetor):
  n = len(vetor)

  for i in range(1, n):
    marcado = vetor[i]

    j = i - 1
    while j >= 0 and marcado < vetor[j]:
      vetor[j + 1] = vetor[j]
      j -= 1
    vetor[j + 1] = marcado

  return vetor

In [ ]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Shell sort

In [ ]:
def shell_sort(vetor):
  intervalo = len(vetor) // 2

  while intervalo > 0:
    for i in range(intervalo, len(vetor)):
      temp = vetor[i]
      j = i
      while j >= intervalo and vetor[j - intervalo] > temp:
        vetor[j] = vetor[j - intervalo]
        j -= intervalo
      vetor[j] = temp
    intervalo //= 2

  return vetor

In [ ]:
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
shell_sort(np.array([8,5,1,4,2,3]))

array([1, 2, 3, 4, 5, 8])

## Merge sort

In [ ]:
def merge_sort(vetor):
  if len(vetor) > 1:
    divisao = len(vetor) // 2
    esquerda = vetor[:divisao].copy()
    direita = vetor[divisao:].copy()

    merge_sort(esquerda)
    merge_sort(direita)

    i = j = k = 0

    # Ordena esquerda e direita
    while i < len(esquerda) and j < len(direita):
      if esquerda[i] < direita[j]:
        vetor[k] = esquerda[i]
        i += 1
      else:
        vetor[k] = direita[j]
        j += 1
      k += 1

    # Ordenação final
    while i < len(esquerda):
      vetor[k] = esquerda[i]
      i += 1
      k += 1
    while j < len(direita):
      vetor[k] = direita[j]
      j += 1
      k += 1
  return vetor

In [ ]:
merge_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [ ]:
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
merge_sort(np.array([38, 27, 43, 3, 9, 82, 10]))

array([ 3,  9, 10, 27, 38, 43, 82])

## Quick sort

In [ ]:
def particao(vetor, inicio, final):
  pivo = vetor[final]
  i = inicio - 1

  for j in range(inicio, final):
    if vetor[j] <= pivo:
      i += 1
      vetor[i], vetor[j] = vetor[j], vetor[i]
  vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
  return i + 1

def quick_sort(vetor, inicio, final):
  if inicio < final:
    posicao = particao(vetor, inicio, final)
    # Esquerda
    quick_sort(vetor, inicio, posicao - 1)
    # Direito
    quick_sort(vetor, posicao + 1, final)
  return vetor

In [ ]:
vetor = np.array([15, 34, 8, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])

In [ ]:
vetor = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Comparativo entre algoritmos

In [ ]:
import random
vetor = []
for _ in range(5000):
  vetor.append(round(random.random(), 4))

In [ ]:
type(vetor)

list

In [ ]:
vetor = np.array(vetor)
type(vetor)

numpy.ndarray

In [ ]:
vetor[:5]

array([0.1323, 0.6192, 0.1069, 0.0134, 0.7862])

In [ ]:
len(vetor)

5000

In [ ]:
%timeit bubble_sort(vetor.copy())

1 loop, best of 3: 7.37 s per loop


In [ ]:
%timeit selection_sort(vetor.copy())

1 loop, best of 3: 3.84 s per loop


In [ ]:
%timeit insertion_sort(vetor.copy())

1 loop, best of 3: 2.92 s per loop


In [ ]:
%timeit shell_sort(vetor.copy())

10 loops, best of 3: 51.3 ms per loop


In [ ]:
%timeit merge_sort(vetor.copy())

10 loops, best of 3: 50.3 ms per loop


In [ ]:
%timeit quick_sort(vetor.copy(), 0, len(vetor) - 1)

10 loops, best of 3: 31.4 ms per loop


## Vetor ordenado

In [ ]:
class VetorOrdenado:
  
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.ultima_posicao = -1
    self.valores = np.empty(self.capacidade, dtype=float)

  def insere(self, valor):
    if self.ultima_posicao == self.capacidade - 1:
      print('Capacidade atingida')
      return
    
    posicao = 0
    for i in range(self.ultima_posicao + 1):
      posicao = i
      if self.valores[i] > valor:
        break
      if i == self.ultima_posicao:
        posicao = i + 1

    x = self.ultima_posicao
    while x >= posicao:
      self.valores[x + 1] = self.valores[x]
      x -= 1
    
    self.valores[posicao] = valor    
    self.ultima_posicao += 1

In [ ]:
def insere_ordenado(valores):
  vetor = VetorOrdenado(len(valores))
  for i in range(len(valores)):
    vetor.insere(i)

In [ ]:
%timeit insere_ordenado(vetor.copy())

1 loop, best of 3: 5.45 s per loop
